name: Transform Design Tokens

on:
  push:
    branches:
      - main

jobs:
  transform-tokens:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Token Tinker
        uses: Design-System-Pro/token-tinker@0.1.0-next.2
        with:
          # Path to the tokens JSON files (relative to the root of your repository)
          tokens-path: ./tokens/
          # Path to output the transformed tokens (relative to the root of your repository)
          build-path: ./build/
          # Specify the export type: "single" for one file, "multiple" for multiple files
          tokens-export-type: multiple
      # You can replace where the build goes according to your needs 👇
      # As an example, you can download it manually from your github action runner.
      - name: Archive tinker results
        uses: actions/upload-artifact@v4
        with:
          name: result
          path: build
