name: Transform Tokens (SCSS by GPT4o)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Debug file visibility
      - name: List files in the repository root
        run: ls -la

      # Run Style Dictionary build
      - name: Transform tokens
        run: npm run build

      # Save generated files as build artifacts (optional)
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: transformed-tokens
          path: build/
